version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run: docker info
      - run: docker build --rm=false -t gridthings/api --build-arg gtcli_key=$GTCLI_KEY .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "feature/circle20" ]; then
              apk update
              apk add py-pip
              pip install awscli
              aws configure set aws_access_key_id $AWSKEY
              aws configure set aws_secret_access_key $AWSSECRETKEY
              aws configure set default.region ap-southeast-2
              aws configure set default.output json
              eval $(aws ecr get-login)
              docker tag gridthings/api:latest 337134270675.dkr.ecr.ap-southeast-2.amazonaws.com/gridthings/api:latest
              docker push 337134270675.dkr.ecr.ap-southeast-2.amazonaws.com/gridthings/api:latest
            fi
